--  --- @class _99.State.Tracking.Options
--  --- @field __request_history _99.Prompt[] | nil
--  --- vj
--  --- @field __request_by_id table<number, _99.Prompt> | nil
--  --- v
--  --- @field __active_marks _99.Mark[] | nil
--
--  --- @class _99.State.Tracking
--  --- @field __request_history _99.Prompt[]
--  --- @field __request_by_id table<number, _99.Prompt>
--  --- @field __active_marks _99.Mark[]
--  local Tracking = {}
--
--  --- @param previous_state
--  function Tracking.new(previous_state)
--  end
--
--
--  return Tracking
--
return {}
